server:
  port: 8888
spring:
  application:
    name: discovery-service
eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/